sudo: required
dist: trusty
language: node_js
node_js:
- '9'
env: DISPLAY=':99.0'
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
before_script:
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  app: behappi
  api_key:
    secure: AdGUEDmnKBRouL9le+tJsQ8TTiQNxleHZm2+OMVZUPZ8F/eX+ftlpQiTsERX0qzKE2NHIFxt2VLb1wu8bUq9TR3b8z4Vvx9dAMyLkUVqiRgYR69c2HT8NLW5y+4Av4S7prqaTN3mdhBM9tQNot+5Mx2aRlxaPjnY7a8txd/14GRjRSpnx2WG6PinTi/SlO/08iltbEuIaoTj6JSNbna68oN18SDBYEOM6EEUGpGOtl5rJRrGQ5WP/aepb06HvCda/D3ht9WUbAvfBP0XB17rQE7RDI0a6cOwnHLRtj8ZSjtDsMf9jftg/efrkSsw9CWzWpp8+sOemOIg4wpSSJidLkkLtogmneg54SK/bVC/I+je66U22ZJmthYi8asxZbw0S2vARR5AJjd2a2ZvbCkwtedoG/TvnCRIpIzI0ye6+whD10hrSvjnCga4zUAru7Aj1XuAzmsVpO70KdeGgfMnNnFpQh/bdRFOBPzrnjTr7lamIZGCr2HRiIz3KSmAoEKSm5VEAqWR1TAeV6qxYt8Fp7xsbL9VeAbcL2brZPzDXkmjst00niu7qGdH3bfrvbkvXUIZnv3d0HdhjU4h7tv2L+W7NfpGoq2lMVp3WAM+jttaM5vpzpKaGDDFNUj1uC7iI8Nps2+fAvN4BulSYUBTVjK8susRx3hSoRa3VmbOufw=
